export const SUPPORTED_LOCALES = ["en", "pt-BR", "es-419"] as const;
export type Locale = (typeof SUPPORTED_LOCALES)[number];
export interface Copy {
  meta: { title: string; description: string };
  nav: string[]; language: string; theme: string; skip: string;
  hero: { intro: string; title: string[]; body: string; scene: string; tabs: string[]; descriptions: string[]; pause: string; play: string };
  hardware: { title: string; body: string; points: [string, string][]; label: string; installed: string; backup: string };
  system: { kicker: string; title: string; body: string; tabs: string[]; descriptions: string[]; caption: string; alt: string[]; importTitle: string; importBody: string; sources: string[]; destination: string; importNote: string };
  team: { kicker: string; title: string; body: string; agentRole: string; agentBody: string; devRole: string; devBody: string; agentTasks: string[]; devTasks: string[]; note: string };
  story: { title: string; body: string; request: string; steps: [string, string][]; caption: string };
  modules: { title: string; body: string; items: [string, string][]; final: string };
  closing: { title: string[]; body: string; note: string; top: string };
}
const en: Copy = {
  meta: { title: "CompanyOS | Your company. One system.", description: "CompanyOS brings your business together: an information system on your own infrastructure, customizable modules, and OS Agent and OS Dev as part of your team." },
  nav: ["Your foundation", "Your system", "Your team"], language: "Language", theme: "Switch color theme", skip: "Skip to content",
  hero: { intro: "Built around your business", title: ["Your company.", "One system."], body: "Your own computer. A system you can shape. AI agents on your team.", scene: "A 3D illustration of CompanyOS: a company-owned computer supports connected business modules, with OS Agent and OS Dev alongside them.", tabs: ["Your computer", "Your system", "Your team"], descriptions: ["The foundation is yours. CompanyOS runs on hardware your company controls.", "Start with connected modules. Bring your data. Make every workflow your own.", "OS Agent does the work. OS Dev evolves the system. Both work with your team."], pause: "Pause animation", play: "Play animation" },
  hardware: { title: "It starts with something you own.", body: "CompanyOS is installed, hosted, and run on your company’s infrastructure. A computer at your office, or a server with the cloud provider you choose.", points: [["Your choice of home", "On premises or in your own cloud environment. You decide where the system lives."], ["Backups, taken care of", "Your business data is backed up automatically."], ["A foundation that stays current", "The agents help keep CompanyOS updated and tailored to your company."]], label: "Company-owned infrastructure", installed: "CompanyOS installed", backup: "Automatic backups" },
  system: { kicker: "The information system", title: "Everything connects. Everything can change.", body: "The familiar tools of business software, with the freedom to make them yours. Customers, conversations, knowledge, and work share one connected foundation.", tabs: ["The whole picture", "Customer conversations", "Organized work"], descriptions: ["See what needs your attention across the company, in one place.", "Keep customer conversations connected to the people and work behind them.", "Turn the way your team works into boards, calendars, and repeatable processes."], caption: "Early product preview. Interface and capabilities continue to evolve.", alt: ["CompanyOS home with company priorities, active work, and sales pipeline", "CompanyOS shared inbox with customer conversations", "CompanyOS event calendar with multi-day events"], importTitle: "Bring the work you’ve already done.", importBody: "Start with your existing records. Import data from spreadsheets and other systems, then organize it around the way your company works.", sources: ["Spreadsheets", "Customer records", "Existing systems"], destination: "Your company’s context", importNote: "A useful starting point. Never a blank slate." },
  team: { kicker: "Meet your new teammates", title: "They don’t just answer. They help move the business forward.", body: "OS Agent and OS Dev are AI agents embedded in CompanyOS, working with your company’s context and alongside your people.", agentRole: "Works in your business.", agentBody: "Ask for an outcome. OS Agent uses the information system and connected tools to organize records, handle tasks, and bring the results back into your company’s work.", devRole: "Works on your system.", devBody: "Describe what needs to change. OS Dev helps customize workflows, extend modules, and build new capabilities as your company evolves.", agentTasks: ["Understands the context", "Coordinates the work", "Keeps information connected"], devTasks: ["Customizes workflows", "Builds new capabilities", "Helps maintain the system"], note: "Your people set the direction. The agents work alongside them." },
  story: { title: "From a spreadsheet to a better way of working.", body: "One beta company tracked its events in a spreadsheet. That became the starting point for an information system built around the team.", request: "“Help us organize our events, travel bookings, and team assignments.”", steps: [["Bring in the existing work", "OS Agent imported the events and organized them into a board."], ["Make it fit the team", "Reusable travel checklists and team labels brought the process together."], ["Extend what’s possible", "An end-date field made multi-day events part of the workflow."]], caption: "Event planning in CompanyOS. Example data shown." },
  modules: { title: "A solid start. An open future.", body: "Start with practical ERP and CRM modules. Add, adapt, and extend them as your business finds its own way of working.", items: [["Relationships", "Customers, companies, and their history."], ["Inbox", "Customer conversations in one place."], ["Pipeline", "Opportunities and the next steps."], ["Boards", "Projects, calendars, and repeatable work."], ["Knowledge", "The context that makes your company yours."], ["Workspaces", "Separate teams, brands, and business contexts."]], final: "These are starting points. Your business defines what comes next." },
  closing: { title: ["Your infrastructure.", "Your information.", "Your CompanyOS."], body: "A company operating system that becomes more yours with every improvement.", note: "In active development. Built with real small businesses.", top: "Back to top" },
};
const ptBR: Copy = {
  meta: { title: "CompanyOS | Sua empresa. Um só sistema.", description: "O CompanyOS conecta sua empresa: um sistema de informação na sua infraestrutura, módulos personalizáveis e OS Agent e OS Dev como parte da equipe." },
  nav: ["Sua base", "Seu sistema", "Sua equipe"], language: "Idioma", theme: "Alternar tema de cores", skip: "Ir para o conteúdo",
  hero: { intro: "Feito para o seu negócio", title: ["Sua empresa.", "Um só sistema."], body: "Seu próprio computador. Um sistema que você pode moldar. Agentes de IA na equipe.", scene: "Ilustração 3D do CompanyOS: um computador da empresa sustenta módulos de negócio conectados, com OS Agent e OS Dev ao lado.", tabs: ["Seu computador", "Seu sistema", "Sua equipe"], descriptions: ["A base é sua. O CompanyOS roda em hardware controlado pela sua empresa.", "Comece com módulos conectados. Traga seus dados. Adapte cada fluxo ao seu negócio.", "OS Agent executa o trabalho. OS Dev evolui o sistema. Os dois trabalham com sua equipe."], pause: "Pausar animação", play: "Reproduzir animação" },
  hardware: { title: "Tudo começa com algo que é seu.", body: "O CompanyOS é instalado, hospedado e executado na infraestrutura da sua empresa. Um computador no escritório ou um servidor no provedor de nuvem que você escolher.", points: [["Você escolhe onde", "Na empresa ou no seu ambiente de nuvem. Você decide onde o sistema fica."], ["Backups automáticos", "Os dados do negócio são copiados automaticamente para backup."], ["Uma base que se mantém atualizada", "Os agentes ajudam a manter o CompanyOS atualizado e adaptado à empresa."]], label: "Infraestrutura da empresa", installed: "CompanyOS instalado", backup: "Backups automáticos" },
  system: { kicker: "O sistema de informação", title: "Tudo se conecta. Tudo pode mudar.", body: "As ferramentas conhecidas dos sistemas de gestão, com liberdade para torná-las suas. Clientes, conversas, conhecimento e trabalho compartilham uma base conectada.", tabs: ["A visão do negócio", "Conversas com clientes", "Trabalho organizado"], descriptions: ["Veja o que precisa de atenção em toda a empresa, em um só lugar.", "Conecte as conversas com clientes às pessoas e ao trabalho por trás delas.", "Transforme a rotina da equipe em quadros, calendários e processos reutilizáveis."], caption: "Prévia do produto em desenvolvimento. A interface e os recursos continuam evoluindo.", alt: ["Início do CompanyOS com prioridades, trabalho ativo e pipeline de vendas", "Caixa de entrada compartilhada do CompanyOS com conversas de clientes", "Calendário de eventos do CompanyOS com eventos de vários dias"], importTitle: "Traga o trabalho que você já fez.", importBody: "Comece com os registros que já existem. Importe dados de planilhas e outros sistemas e organize tudo de acordo com a forma de trabalhar da empresa.", sources: ["Planilhas", "Registros de clientes", "Outros sistemas"], destination: "O contexto da sua empresa", importNote: "Um ponto de partida útil. Nunca uma página em branco." },
  team: { kicker: "Conheça seus novos colegas", title: "Eles vão além das respostas. Ajudam o negócio a avançar.", body: "OS Agent e OS Dev são agentes de IA integrados ao CompanyOS. Trabalham com o contexto da empresa e ao lado das pessoas.", agentRole: "Trabalha no seu negócio.", agentBody: "Peça um resultado. OS Agent usa o sistema de informação e ferramentas conectadas para organizar registros, executar tarefas e trazer os resultados para o trabalho da empresa.", devRole: "Trabalha no seu sistema.", devBody: "Descreva o que precisa mudar. OS Dev ajuda a personalizar fluxos, ampliar módulos e criar recursos conforme a empresa evolui.", agentTasks: ["Entende o contexto", "Coordena o trabalho", "Mantém as informações conectadas"], devTasks: ["Personaliza fluxos", "Cria novos recursos", "Ajuda a manter o sistema"], note: "As pessoas definem a direção. Os agentes trabalham ao lado delas." },
  story: { title: "De uma planilha a uma forma melhor de trabalhar.", body: "Uma empresa do beta controlava seus eventos em uma planilha. Ela virou o ponto de partida de um sistema de informação feito para a equipe.", request: "“Ajude a organizar nossos eventos, reservas de viagem e equipes.”", steps: [["Trazer o trabalho existente", "OS Agent importou os eventos e organizou tudo em um quadro."], ["Adaptar à equipe", "Checklists reutilizáveis de viagem e etiquetas de equipe conectaram o processo."], ["Ampliar as possibilidades", "Um campo de data final incorporou eventos de vários dias ao fluxo."]], caption: "Planejamento de eventos no CompanyOS. Dados de exemplo." },
  modules: { title: "Uma base sólida. Um futuro aberto.", body: "Comece com módulos práticos de ERP e CRM. Adicione, adapte e amplie conforme o negócio encontra sua própria forma de trabalhar.", items: [["Relacionamentos", "Clientes, empresas e seus históricos."], ["Caixa de entrada", "Conversas com clientes em um só lugar."], ["Pipeline", "Oportunidades e próximos passos."], ["Quadros", "Projetos, calendários e rotinas de trabalho."], ["Conhecimento", "O contexto que torna sua empresa única."], ["Espaços", "Equipes, marcas e contextos de negócio separados."]], final: "Estes são pontos de partida. Sua empresa define o que vem depois." },
  closing: { title: ["Sua infraestrutura.", "Sua informação.", "Seu CompanyOS."], body: "Um sistema operacional para a empresa que fica mais seu a cada melhoria.", note: "Em desenvolvimento ativo. Construído com pequenos negócios reais.", top: "Voltar ao início" },
};
const es419: Copy = {
  meta: { title: "CompanyOS | Tu empresa. Un solo sistema.", description: "CompanyOS conecta tu empresa: un sistema de información en tu infraestructura, módulos personalizables y OS Agent y OS Dev como parte del equipo." },
  nav: ["Tu base", "Tu sistema", "Tu equipo"], language: "Idioma", theme: "Cambiar tema de color", skip: "Ir al contenido",
  hero: { intro: "Hecho para tu negocio", title: ["Tu empresa.", "Un solo sistema."], body: "Tu propia computadora. Un sistema que puedes adaptar. Agentes de IA en tu equipo.", scene: "Ilustración 3D de CompanyOS: una computadora de la empresa sostiene módulos de negocio conectados, con OS Agent y OS Dev a su lado.", tabs: ["Tu computadora", "Tu sistema", "Tu equipo"], descriptions: ["La base es tuya. CompanyOS funciona en hardware que tu empresa controla.", "Empieza con módulos conectados. Trae tus datos. Adapta cada flujo a tu negocio.", "OS Agent hace el trabajo. OS Dev hace evolucionar el sistema. Ambos trabajan con tu equipo."], pause: "Pausar animación", play: "Reproducir animación" },
  hardware: { title: "Todo empieza con algo que es tuyo.", body: "CompanyOS se instala, aloja y ejecuta en la infraestructura de tu empresa. Una computadora en la oficina o un servidor con el proveedor de nube que elijas.", points: [["Tú eliges dónde", "En tus instalaciones o en tu propio entorno de nube. Tú decides dónde vive el sistema."], ["Respaldos automáticos", "Los datos del negocio se respaldan automáticamente."], ["Una base que se mantiene al día", "Los agentes ayudan a mantener CompanyOS actualizado y adaptado a tu empresa."]], label: "Infraestructura de la empresa", installed: "CompanyOS instalado", backup: "Respaldos automáticos" },
  system: { kicker: "El sistema de información", title: "Todo se conecta. Todo puede cambiar.", body: "Las herramientas conocidas del software de gestión, con libertad para hacerlas tuyas. Clientes, conversaciones, conocimiento y trabajo comparten una base conectada.", tabs: ["La visión del negocio", "Conversaciones", "Trabajo organizado"], descriptions: ["Ve lo que necesita atención en toda la empresa, en un solo lugar.", "Conecta las conversaciones con clientes con las personas y el trabajo detrás de ellas.", "Convierte la forma de trabajar del equipo en tableros, calendarios y procesos reutilizables."], caption: "Vista previa del producto en desarrollo. La interfaz y las capacidades siguen evolucionando.", alt: ["Inicio de CompanyOS con prioridades, trabajo activo y pipeline de ventas", "Bandeja de entrada compartida de CompanyOS con conversaciones de clientes", "Calendario de CompanyOS con eventos de varios días"], importTitle: "Trae el trabajo que ya hiciste.", importBody: "Empieza con los registros que ya tienes. Importa datos de hojas de cálculo y otros sistemas, y organízalos según la forma de trabajar de tu empresa.", sources: ["Hojas de cálculo", "Registros de clientes", "Otros sistemas"], destination: "El contexto de tu empresa", importNote: "Un punto de partida útil. Nunca una página en blanco." },
  team: { kicker: "Conoce a tus nuevos compañeros", title: "Van más allá de las respuestas. Ayudan al negocio a avanzar.", body: "OS Agent y OS Dev son agentes de IA integrados en CompanyOS. Trabajan con el contexto de tu empresa y junto a tu gente.", agentRole: "Trabaja en tu negocio.", agentBody: "Pide un resultado. OS Agent usa el sistema de información y las herramientas conectadas para organizar registros, ejecutar tareas y devolver los resultados al trabajo de tu empresa.", devRole: "Trabaja en tu sistema.", devBody: "Describe lo que necesita cambiar. OS Dev ayuda a personalizar flujos, ampliar módulos y crear capacidades a medida que tu empresa evoluciona.", agentTasks: ["Entiende el contexto", "Coordina el trabajo", "Mantiene la información conectada"], devTasks: ["Personaliza flujos", "Crea nuevas capacidades", "Ayuda a mantener el sistema"], note: "Tu gente marca la dirección. Los agentes trabajan a su lado." },
  story: { title: "De una hoja de cálculo a una mejor forma de trabajar.", body: "Una empresa del beta controlaba sus eventos en una hoja de cálculo. Ese fue el punto de partida de un sistema de información hecho para el equipo.", request: "“Ayúdanos a organizar nuestros eventos, reservas de viaje y equipos.”", steps: [["Traer el trabajo existente", "OS Agent importó los eventos y los organizó en un tablero."], ["Adaptarlo al equipo", "Listas de viaje reutilizables y etiquetas de equipo conectaron el proceso."], ["Ampliar las posibilidades", "Un campo de fecha final incorporó eventos de varios días al flujo."]], caption: "Planificación de eventos en CompanyOS. Datos de ejemplo." },
  modules: { title: "Una base sólida. Un futuro abierto.", body: "Empieza con módulos prácticos de ERP y CRM. Agrega, adapta y amplía mientras tu negocio encuentra su propia forma de trabajar.", items: [["Relaciones", "Clientes, empresas y sus historiales."], ["Bandeja de entrada", "Conversaciones con clientes en un solo lugar."], ["Pipeline", "Oportunidades y próximos pasos."], ["Tableros", "Proyectos, calendarios y trabajo reutilizable."], ["Conocimiento", "El contexto que hace única a tu empresa."], ["Espacios", "Equipos, marcas y contextos de negocio separados."]], final: "Estos son puntos de partida. Tu empresa define lo que sigue." },
  closing: { title: ["Tu infraestructura.", "Tu información.", "Tu CompanyOS."], body: "Un sistema operativo para tu empresa que se vuelve más tuyo con cada mejora.", note: "En desarrollo activo. Creado con pequeños negocios reales.", top: "Volver al inicio" },
};
export const COPY: Record<Locale, Copy> = { en, "pt-BR": ptBR, "es-419": es419 };
export function normalizeLocale(value: string | null | undefined): Locale | null {
  const normalized = value?.toLowerCase();
  if (normalized?.startsWith("pt")) return "pt-BR";
  if (normalized?.startsWith("es")) return "es-419";
  if (normalized?.startsWith("en")) return "en";
  return null;
}
