export const SUPPORTED_LOCALES = ["en", "pt-BR", "es-419"] as const;

export type Locale = (typeof SUPPORTED_LOCALES)[number];

const en = {
  meta: {
    title: "OperateOS — Business software that becomes yours.",
    description: "OperateOS is a private, adaptable ERP and CRM for small businesses, with agents that learn the business, automate work, and extend the system.",
    ogDescription: "A private business system that runs on your own computer, adapts to your company, and comes with agents that do real work.",
  },
  language: { label: "Language", en: "English", pt: "Português (Brasil)", es: "Español (Latinoamérica)" },
  nav: { aria: "Main navigation", homeAria: "OperateOS home", system: "Why change", work: "How it works", modules: "What’s inside", beta: "Beta", ownership: "Why it matters", access: "Now in beta" },
  hero: {
    title: "Business software should fit your business.",
    subtitle: "OperateOS is a private, adaptable ERP and CRM that runs on your own computer—with agents that learn how your business works, handle real tasks, and help the system grow with you.",
    primaryCta: "Join the beta waitlist", secondaryCta: "Get in touch", ctaAria: "OperateOS beta and contact options",
    stageAria: "OperateOS connecting the business system, private agents, custom capabilities, and company-owned data", status: "Private", identity: "Your business, finally running on a system built around it.", factsLabel: "OperateOS product details",
    facts: [["System", "ERP + CRM"], ["Runs on", "Your computer"]], scroll: "See what changes",
  },
  systemParts: [
    ["One business system.", "Customers, sales, work, knowledge, and conversations come together.", "part-system"],
    ["Agents that know the business.", "OS Operator learns the context and turns requests into real work.", "part-agent"],
    ["Made to be changed.", "Add modules, workflows, and capabilities as your needs evolve.", "part-extendable"],
    ["Your computer. Your data.", "OperateOS runs on hardware your business controls.", "part-hardware"],
  ],
  system: {
    kicker: "The problem with old SaaS", title: "Your business changes. Your software should too.",
    body: "Small businesses have spent years adapting their work to rigid subscriptions. One app for customers, another for projects, more for messages and reports—each with its own bill, limits, and copy of your data. OperateOS turns that relationship around.",
    capabilitiesAria: "Before and after OperateOS", advantage: "Before and after", advantageTitle: "Stop bending the business around someone else’s software.",
    advantageBody: "Start with a practical ERP and CRM, then shape the information system around the way your company actually sells, serves customers, and gets work done.",
  },
  capabilities: [
    ["Before", "Too many subscriptions.", "Work is scattered across apps, spreadsheets, logins, and monthly bills."],
    ["With OperateOS", "One connected picture.", "Customers, sales, tasks, conversations, and knowledge can work together."],
    ["Before", "Rigid workflows.", "The software decides what fields, steps, and reports your business must use."],
    ["With OperateOS", "A system that adapts.", "Change a workflow, create a module, or add a capability when the need appears."],
  ],
  layers: [
    ["Start useful", "ERP and CRM essentials from day one", "Begin with connected tools for customers, sales, communication, work, and company knowledge—not an empty box you have to design.", "violet"],
    ["Make it yours", "Your workflows, language, and priorities", "OperateOS is built to match the core of your business instead of forcing every company into the same template.", "cyan"],
    ["Keep improving", "New needs become new capabilities", "As the business grows, your system can gain modules and workflows inspired by leading business SaaS—without becoming another pile of subscriptions.", "lime"],
    ["Stay in control", "A private system on your own computer", "Your business controls the installation and its data. Approvals and permissions keep consequential actions in human hands.", "coral"],
  ],
  work: {
    kicker: "Agents inside the business", titleBefore: "Meet OS Operator: context that turns into ", emphasis: "action", titleAfter: ".",
    you: "You", question: "“Help us organize the events we attend throughout the year.”",
    steps: [["Learns the need", "OS Operator asks what must be tracked and how the team works"], ["Finds the right approach", "It can recommend a better workflow, not just repeat the old one"], ["Builds the work", "The agent creates records, organizes information, and handles repetitive steps"], ["Keeps you in control", "You review consequential changes before they happen"]],
    recommended: "What OS Operator can do", action: "Turn a request into finished work", result: "The agent works across OperateOS, your business context, and connected tools", approve: "You approve", approveAria: "Example human approval control", confirmation: "You set the direction. OS Operator does the legwork and brings the result back to the system.",
  },
  structure: {
    kicker: "A real beta story", title: "A spreadsheet became an event system—without days of setup.",
    body: "A beta company attends events all year and managed everything in a spreadsheet. OS Operator recommended and created a Kanban board, made a reusable card with a checklist for hotel reservations, flights, and rental cars, and added labels for assigning teams. It also suggested an end-date field for multi-day events, then imported every existing event—saving hours of data entry.",
    prompt: "“We need to track every event, travel booking, and team assignment. Our events are in this spreadsheet.”",
    outputAria: "The event planning board created by OS Operator in OperateOS", created: "Created by OS Operator in Boards", ready: "Imported and ready", newProject: "Live beta workflow", project: "Annual event operations", owner: "Built around the team’s process",
    summary: [["1", "spreadsheet imported"], ["3", "travel checks"], ["Teams", "assigned with labels"], ["Dates", "start and end"]],
    columns: [["To plan", [["Industry Expo", "Hotel · Flight · Rental car"], ["Partner Summit", "Team label · Travel checklist"]]], ["In progress", [["Customer Conference", "Travel being booked"], ["Regional Fair", "Operations team assigned"]]], ["Ready", [["Spring Showcase", "All checklist items complete"], ["Leadership Forum", "Dates and team confirmed"]]]],
    later: "OS Operator’s suggestion", update: "“Events span more than one day. Let’s add an end-date field.”", updated: "The board was extended to fit the real work",
  },
  development: {
    kicker: "Software that can grow with you", title: "OS Developer is the engineer on your agent team.",
    body: "When the business needs more than a setting or template, OS Developer can modify and extend OperateOS itself. Describe the outcome, review the approach, and receive a tested change to approve—without waiting for a SaaS vendor’s roadmap.",
    mode: "OS Developer", connected: "Ready to build", agentLabel: "OS Developer", history: "Business improvements", next: "The system keeps getting better",
    historyItems: [["Event end dates", "Product extension · delivered"], ["Vendor onboarding", "Custom workflow · ready"], ["Customer inbox", "Connected module · active"]],
    user: "Our events need an end date, not just a due date.", agent: "I’ll extend the card so every event can have a start and end date, keep the calendar consistent, and return the change for review.",
    progress: ["Need understood", "Experience updated", "Existing workflow preserved", "Tested and ready for review"], newCapability: "Built for the business", module: "Event date range", moduleBody: "A focused improvement that now belongs to the company’s system.", appears: "Reviewed before it goes live",
  },
  modulesSection: {
    kicker: "For example—and much more", title: "Start with the essentials. Keep adding what matters.", body: "OperateOS is an ERP and CRM in constant development. These are examples of what is available today, not the limits of the product. We will keep expanding the system with the most valuable capabilities found in leading business SaaS—and your company can extend it for the work that makes you different.", aria: "Examples of OperateOS modules",
    workspaceKicker: "Built for any small business", workspaceTitle: "Different industries. Different workflows. One adaptable foundation.", workspaceBody: "A retailer, studio, contractor, clinic, or service company should not have to work the same way. Each workspace keeps its own people, files, knowledge, branding, and agent context while administration stays organized.", workspaceAria: "Examples of separate small-business workspaces", workspaceTypes: ["Retail", "Creative", "Services"], sharedAdmin: "One private installation",
  },
  modules: [["Home", "Your operating picture"], ["Inbox", "Website chat, text, and email together"], ["Pipeline", "Sales opportunities and next steps"], ["Relationships", "Contacts, companies, and history"], ["Ads", "Google and Meta performance with guarded actions"], ["Boards", "Kanban, calendar, templates, and checklists"], ["Knowledge", "Your company’s source of truth"], ["Workspaces", "Separate teams, brands, and context"], ["Agent Chat", "Ask, review, and act in one place"]],
  beta: {
    kicker: "Now in beta testing", title: "Help shape the business system you always wished existed.", body: "We’re working with small businesses from any industry to test OperateOS against real operations. Join the waitlist to tell us where your current software gets in the way, or get in touch for more information.",
    promiseLabel: "What beta means", promise: "Real workflows, close collaboration, and a product that improves from the work small businesses actually need—not from a generic feature checklist.",
    cardsAria: "Ways to connect with OperateOS", cards: [["01", "Join the beta waitlist", "Share your business and the problems you want the system to solve.", "Join the waitlist", "mailto:hello@operaos.ai?subject=Join%20the%20OperateOS%20beta%20waitlist"], ["02", "Get in touch", "Ask questions, discuss your needs, or request more information.", "Contact us", "mailto:hello@operaos.ai?subject=OperateOS%20information"]],
    noteLabel: "Built with beta users", noteTitle: "Your real work guides what comes next.", noteBody: "We’re expanding OperateOS at a deliberate pace, prioritizing useful capabilities, dependable workflows, and changes that make small businesses easier to run.",
  },
  ownership: {
    kicker: "A better long-term choice", lineOne: "Your system.", lineTwo: "Your data.", lineThree: "Your way of ", emphasis: "working.", body: "Instead of renting the same rigid tools forever, build an information system that becomes more valuable as it learns the business and adapts to it.",
    proofs: [["Runs on your computer", "Your business controls where OperateOS and its records live."], ["Private by design", "Company knowledge stays within your business-controlled system."], ["Human approval", "Consequential agent actions wait for your decision."], ["Built to last", "Backups and protected credentials help safeguard the system."]],
    closing: "Stop adapting to old software.", closingSecond: "Start building the system your business deserves.", access: "OperateOS · Beta testing", primaryCta: "Join the beta waitlist", secondaryCta: "Get in touch",
  },
};

export type Copy = typeof en;

const ptBR: Copy = {
  meta: { title: "OperateOS — O software que se torna seu.", description: "OperateOS é um ERP e CRM privado e adaptável para pequenos negócios, com agentes que aprendem sobre a empresa, automatizam o trabalho e ampliam o sistema.", ogDescription: "Um sistema privado que roda no seu próprio computador, adapta-se à sua empresa e vem com agentes que realizam trabalho de verdade." },
  language: { label: "Idioma", en: "English", pt: "Português (Brasil)", es: "Español (Latinoamérica)" },
  nav: { aria: "Navegação principal", homeAria: "Página inicial do OperateOS", system: "Por que mudar", work: "Como funciona", modules: "O que está incluído", beta: "Beta", ownership: "Por que importa", access: "Agora em beta" },
  hero: { title: "O software deveria se adaptar ao seu negócio.", subtitle: "OperateOS é um ERP e CRM privado e adaptável que roda no seu próprio computador — com agentes que aprendem como sua empresa funciona, realizam tarefas de verdade e ajudam o sistema a crescer com você.", primaryCta: "Entrar na lista de espera", secondaryCta: "Falar com a gente", ctaAria: "Opções para participar do beta e entrar em contato", stageAria: "OperateOS conectando o sistema do negócio, agentes privados, recursos personalizados e dados sob controle da empresa", status: "Privado", identity: "Seu negócio finalmente em um sistema criado ao redor dele.", factsLabel: "Detalhes do produto OperateOS", facts: [["Sistema", "ERP + CRM"], ["Roda no", "Seu computador"]], scroll: "Veja o que muda" },
  systemParts: [["Um só sistema.", "Clientes, vendas, trabalho, conhecimento e conversas reunidos.", "part-system"], ["Agentes que conhecem o negócio.", "OS Operator aprende o contexto e transforma pedidos em trabalho real.", "part-agent"], ["Feito para mudar.", "Adicione módulos, fluxos e recursos conforme suas necessidades evoluem.", "part-extendable"], ["Seu computador. Seus dados.", "OperateOS roda em uma máquina controlada pelo seu negócio.", "part-hardware"]],
  system: { kicker: "O problema dos SaaS antigos", title: "Seu negócio muda. Seu software também deveria mudar.", body: "Pequenos negócios passaram anos adaptando o trabalho a assinaturas rígidas. Um aplicativo para clientes, outro para projetos, mais alguns para mensagens e relatórios — cada um com sua conta, seus limites e uma cópia dos seus dados. OperateOS inverte essa relação.", capabilitiesAria: "Antes e depois do OperateOS", advantage: "Antes e depois", advantageTitle: "Pare de moldar o negócio ao software de outra empresa.", advantageBody: "Comece com um ERP e CRM prático e molde o sistema de informação à forma como sua empresa vende, atende clientes e realiza o trabalho." },
  capabilities: [["Antes", "Assinaturas demais.", "O trabalho fica espalhado em aplicativos, planilhas, logins e cobranças mensais."], ["Com OperateOS", "Uma visão conectada.", "Clientes, vendas, tarefas, conversas e conhecimento podem trabalhar juntos."], ["Antes", "Fluxos rígidos.", "O software decide quais campos, etapas e relatórios seu negócio deve usar."], ["Com OperateOS", "Um sistema que se adapta.", "Mude um fluxo, crie um módulo ou adicione um recurso quando a necessidade surgir."]],
  layers: [["Útil desde o início", "O essencial de ERP e CRM desde o primeiro dia", "Comece com ferramentas conectadas para clientes, vendas, comunicação, trabalho e conhecimento da empresa — não com uma caixa vazia para configurar.", "violet"], ["Do seu jeito", "Seus fluxos, sua linguagem e suas prioridades", "OperateOS acompanha a essência do seu negócio, sem obrigar todas as empresas a usar o mesmo modelo.", "cyan"], ["Sempre evoluindo", "Novas necessidades viram novos recursos", "Conforme o negócio cresce, o sistema ganha módulos e fluxos inspirados nos melhores SaaS — sem virar outra pilha de assinaturas.", "lime"], ["Sempre no controle", "Um sistema privado no seu computador", "Seu negócio controla a instalação e os dados. Aprovações e permissões mantêm decisões importantes nas mãos das pessoas.", "coral"]],
  work: { kicker: "Agentes dentro do negócio", titleBefore: "Conheça OS Operator: contexto que vira ", emphasis: "ação", titleAfter: ".", you: "Você", question: "“Ajude a organizar os eventos dos quais participamos durante o ano.”", steps: [["Entende a necessidade", "OS Operator pergunta o que precisa ser controlado e como a equipe trabalha"], ["Encontra o melhor caminho", "Pode recomendar um fluxo melhor, em vez de apenas repetir o antigo"], ["Coloca o trabalho em prática", "O agente cria registros, organiza informações e cuida das etapas repetitivas"], ["Mantém você no controle", "Você revisa mudanças importantes antes que elas aconteçam"]], recommended: "O que OS Operator pode fazer", action: "Transformar um pedido em trabalho concluído", result: "O agente trabalha no OperateOS, com o contexto do negócio e ferramentas conectadas", approve: "Você aprova", approveAria: "Exemplo de controle de aprovação humana", confirmation: "Você define a direção. OS Operator cuida do trabalho e traz o resultado de volta ao sistema." },
  structure: { kicker: "Uma história real do beta", title: "Uma planilha virou um sistema de eventos — sem dias de configuração.", body: "Uma empresa do beta participa de eventos o ano todo e controlava tudo em uma planilha. OS Operator recomendou e criou um quadro Kanban, montou um cartão reutilizável com checklist para hotel, voos e aluguel de carro e adicionou etiquetas para definir as equipes. Também sugeriu um campo de data final para eventos de vários dias e importou todos os eventos existentes — poupando horas de digitação.", prompt: "“Precisamos controlar cada evento, as reservas de viagem e as equipes. Nossos eventos estão nesta planilha.”", outputAria: "O quadro de eventos criado por OS Operator no OperateOS", created: "Criado por OS Operator em Quadros", ready: "Importado e pronto", newProject: "Fluxo real do beta", project: "Operação anual de eventos", owner: "Criado para o processo da equipe", summary: [["1", "planilha importada"], ["3", "itens de viagem"], ["Equipes", "definidas por etiquetas"], ["Datas", "de início e fim"]], columns: [["A planejar", [["Feira do setor", "Hotel · Voo · Carro alugado"], ["Encontro de parceiros", "Etiqueta da equipe · Checklist de viagem"]]], ["Em andamento", [["Conferência de clientes", "Reservas em andamento"], ["Feira regional", "Equipe de operações definida"]]], ["Pronto", [["Mostra de primavera", "Checklist concluído"], ["Fórum de liderança", "Datas e equipe confirmadas"]]]], later: "Sugestão do OS Operator", update: "“Eventos duram mais de um dia. Vamos adicionar um campo de data final.”", updated: "O quadro foi ampliado para acompanhar o trabalho real" },
  development: { kicker: "Software que cresce com você", title: "OS Developer é o engenheiro da sua equipe de agentes.", body: "Quando o negócio precisa de algo além de uma configuração ou modelo, OS Developer pode modificar e ampliar o próprio OperateOS. Descreva o resultado, revise a proposta e receba uma mudança testada para aprovar — sem depender do cronograma de um fornecedor de SaaS.", mode: "OS Developer", connected: "Pronto para criar", agentLabel: "OS Developer", history: "Melhorias do negócio", next: "O sistema continua melhorando", historyItems: [["Data final de eventos", "Extensão do produto · entregue"], ["Cadastro de fornecedores", "Fluxo personalizado · pronto"], ["Caixa de entrada", "Módulo conectado · ativo"]], user: "Nossos eventos precisam de data final, não apenas uma data de entrega.", agent: "Vou ampliar o cartão para que cada evento tenha datas de início e fim, manter o calendário consistente e devolver a mudança para revisão.", progress: ["Necessidade entendida", "Experiência atualizada", "Fluxo existente preservado", "Testado e pronto para revisão"], newCapability: "Criado para o negócio", module: "Período do evento", moduleBody: "Uma melhoria específica que agora faz parte do sistema da empresa.", appears: "Revisado antes de entrar no ar" },
  modulesSection: { kicker: "Por exemplo — e muito mais", title: "Comece com o essencial. Adicione o que importa.", body: "OperateOS é um ERP e CRM em constante desenvolvimento. Estes são exemplos do que existe hoje, não os limites do produto. Continuaremos ampliando o sistema com os recursos mais valiosos dos principais SaaS — e sua empresa poderá estendê-lo para o trabalho que a torna única.", aria: "Exemplos de módulos do OperateOS", workspaceKicker: "Feito para qualquer pequeno negócio", workspaceTitle: "Setores diferentes. Fluxos diferentes. Uma base adaptável.", workspaceBody: "Uma loja, estúdio, construtora, clínica ou prestadora de serviços não deveria trabalhar da mesma forma. Cada espaço mantém suas pessoas, arquivos, conhecimento, marca e contexto dos agentes, enquanto a administração permanece organizada.", workspaceAria: "Exemplos de espaços separados para pequenos negócios", workspaceTypes: ["Varejo", "Criação", "Serviços"], sharedAdmin: "Uma instalação privada" },
  modules: [["Início", "Sua visão da operação"], ["Caixa de entrada", "Chat do site, SMS e e-mail reunidos"], ["Pipeline", "Oportunidades e próximos passos"], ["Relacionamentos", "Contatos, empresas e histórico"], ["Anúncios", "Google e Meta com ações controladas"], ["Quadros", "Kanban, calendário, modelos e checklists"], ["Conhecimento", "A fonte da verdade da empresa"], ["Espaços", "Equipes, marcas e contextos separados"], ["Chat com agentes", "Peça, revise e aja em um só lugar"]],
  beta: { kicker: "Agora em testes beta", title: "Ajude a criar o sistema que você sempre quis para o seu negócio.", body: "Estamos trabalhando com pequenos negócios de qualquer setor para testar o OperateOS em operações reais. Entre na lista de espera e conte onde seu software atual atrapalha, ou fale com a gente para saber mais.", promiseLabel: "O que significa beta", promise: "Fluxos reais, colaboração próxima e um produto que evolui a partir do que os pequenos negócios realmente precisam — não de uma lista genérica de recursos.", cardsAria: "Formas de falar com o OperateOS", cards: [["01", "Entrar na lista de espera", "Conte sobre seu negócio e os problemas que você quer resolver.", "Entrar na lista", "mailto:hello@operaos.ai?subject=Lista%20de%20espera%20do%20beta%20OperateOS"], ["02", "Falar com a gente", "Tire dúvidas, converse sobre suas necessidades ou peça mais informações.", "Entrar em contato", "mailto:hello@operaos.ai?subject=Informa%C3%A7%C3%B5es%20sobre%20OperateOS"]], noteLabel: "Criado com usuários beta", noteTitle: "Seu trabalho real orienta o que vem depois.", noteBody: "Estamos ampliando o OperateOS com cuidado, priorizando recursos úteis, fluxos confiáveis e mudanças que tornam pequenos negócios mais fáceis de administrar." },
  ownership: { kicker: "Uma escolha melhor a longo prazo", lineOne: "Seu sistema.", lineTwo: "Seus dados.", lineThree: "Seu jeito de ", emphasis: "trabalhar.", body: "Em vez de alugar as mesmas ferramentas rígidas para sempre, construa um sistema de informação que se torna mais valioso à medida que aprende e se adapta ao negócio.", proofs: [["Roda no seu computador", "Seu negócio controla onde o OperateOS e seus registros ficam."], ["Privado por princípio", "O conhecimento da empresa fica no sistema controlado pelo negócio."], ["Aprovação humana", "Ações importantes dos agentes aguardam sua decisão."], ["Feito para durar", "Backups e credenciais protegidas ajudam a manter o sistema seguro."]], closing: "Pare de se adaptar a software antigo.", closingSecond: "Comece a criar o sistema que seu negócio merece.", access: "OperateOS · Testes beta", primaryCta: "Entrar na lista de espera", secondaryCta: "Falar com a gente" },
};

const es419: Copy = {
  meta: { title: "OperateOS — El software que se vuelve tuyo.", description: "OperateOS es un ERP y CRM privado y adaptable para pequeños negocios, con agentes que aprenden sobre la empresa, automatizan el trabajo y amplían el sistema.", ogDescription: "Un sistema privado que funciona en tu propia computadora, se adapta a tu empresa y viene con agentes que hacen trabajo real." },
  language: { label: "Idioma", en: "English", pt: "Português (Brasil)", es: "Español (Latinoamérica)" },
  nav: { aria: "Navegación principal", homeAria: "Inicio de OperateOS", system: "Por qué cambiar", work: "Cómo funciona", modules: "Qué incluye", beta: "Beta", ownership: "Por qué importa", access: "Ahora en beta" },
  hero: { title: "El software debería adaptarse a tu negocio.", subtitle: "OperateOS es un ERP y CRM privado y adaptable que funciona en tu propia computadora, con agentes que aprenden cómo trabaja tu empresa, realizan tareas reales y ayudan al sistema a crecer contigo.", primaryCta: "Unirme a la lista de espera", secondaryCta: "Contactarnos", ctaAria: "Opciones para el beta y contacto", stageAria: "OperateOS conectando el sistema del negocio, agentes privados, capacidades personalizadas y datos bajo control de la empresa", status: "Privado", identity: "Tu negocio, por fin en un sistema creado a su medida.", factsLabel: "Detalles del producto OperateOS", facts: [["Sistema", "ERP + CRM"], ["Funciona en", "Tu computadora"]], scroll: "Descubre qué cambia" },
  systemParts: [["Un solo sistema.", "Clientes, ventas, trabajo, conocimiento y conversaciones conectados.", "part-system"], ["Agentes que conocen el negocio.", "OS Operator aprende el contexto y convierte pedidos en trabajo real.", "part-agent"], ["Hecho para cambiar.", "Agrega módulos, flujos y capacidades cuando evolucionen tus necesidades.", "part-extendable"], ["Tu computadora. Tus datos.", "OperateOS funciona en una máquina controlada por tu negocio.", "part-hardware"]],
  system: { kicker: "El problema del SaaS antiguo", title: "Tu negocio cambia. Tu software también debería cambiar.", body: "Los pequeños negocios llevan años adaptando su trabajo a suscripciones rígidas. Una aplicación para clientes, otra para proyectos y varias más para mensajes e informes: cada una con su factura, sus límites y una copia de tus datos. OperateOS invierte esa relación.", capabilitiesAria: "Antes y después de OperateOS", advantage: "Antes y después", advantageTitle: "Deja de moldear el negocio al software de otros.", advantageBody: "Empieza con un ERP y CRM práctico y adapta el sistema de información a la forma en que tu empresa vende, atiende a sus clientes y hace el trabajo." },
  capabilities: [["Antes", "Demasiadas suscripciones.", "El trabajo queda disperso entre aplicaciones, hojas de cálculo, accesos y pagos mensuales."], ["Con OperateOS", "Una visión conectada.", "Clientes, ventas, tareas, conversaciones y conocimiento pueden trabajar juntos."], ["Antes", "Flujos rígidos.", "El software decide qué campos, pasos e informes debe usar tu negocio."], ["Con OperateOS", "Un sistema que se adapta.", "Cambia un flujo, crea un módulo o agrega una capacidad cuando aparezca la necesidad."]],
  layers: [["Útil desde el inicio", "Lo esencial de ERP y CRM desde el primer día", "Empieza con herramientas conectadas para clientes, ventas, comunicación, trabajo y conocimiento de la empresa; no con una caja vacía por configurar.", "violet"], ["Hazlo tuyo", "Tus flujos, tu lenguaje y tus prioridades", "OperateOS sigue la esencia de tu negocio, en lugar de obligar a todas las empresas a usar la misma plantilla.", "cyan"], ["Mejora continua", "Las nuevas necesidades se vuelven capacidades", "A medida que el negocio crece, el sistema suma módulos y flujos inspirados en el mejor SaaS, sin convertirse en otra pila de suscripciones.", "lime"], ["Mantén el control", "Un sistema privado en tu computadora", "Tu negocio controla la instalación y sus datos. Las aprobaciones y permisos mantienen las decisiones importantes en manos de las personas.", "coral"]],
  work: { kicker: "Agentes dentro del negocio", titleBefore: "Conoce a OS Operator: contexto que se convierte en ", emphasis: "acción", titleAfter: ".", you: "Tú", question: "“Ayúdanos a organizar los eventos a los que asistimos durante el año.”", steps: [["Entiende la necesidad", "OS Operator pregunta qué hay que controlar y cómo trabaja el equipo"], ["Encuentra el mejor enfoque", "Puede recomendar un flujo mejor en vez de limitarse a repetir el anterior"], ["Hace el trabajo", "El agente crea registros, organiza información y resuelve los pasos repetitivos"], ["Te mantiene al mando", "Revisas los cambios importantes antes de que ocurran"]], recommended: "Lo que OS Operator puede hacer", action: "Convertir un pedido en trabajo terminado", result: "El agente trabaja en OperateOS, con el contexto del negocio y las herramientas conectadas", approve: "Tú apruebas", approveAria: "Ejemplo de control de aprobación humana", confirmation: "Tú marcas la dirección. OS Operator hace el trabajo y devuelve el resultado al sistema." },
  structure: { kicker: "Una historia real del beta", title: "Una hoja de cálculo se convirtió en un sistema de eventos, sin días de configuración.", body: "Una empresa del beta asiste a eventos todo el año y llevaba el control en una hoja de cálculo. OS Operator recomendó y creó un tablero Kanban, preparó una tarjeta reutilizable con una lista para hoteles, vuelos y autos de alquiler, y agregó etiquetas para asignar equipos. También sugirió un campo de fecha final para eventos de varios días e importó todos los eventos existentes, ahorrando horas de captura manual.", prompt: "“Necesitamos controlar cada evento, las reservas de viaje y los equipos. Nuestros eventos están en esta hoja de cálculo.”", outputAria: "El tablero de eventos creado por OS Operator en OperateOS", created: "Creado por OS Operator en Tableros", ready: "Importado y listo", newProject: "Flujo real del beta", project: "Operación anual de eventos", owner: "Creado para el proceso del equipo", summary: [["1", "hoja importada"], ["3", "controles de viaje"], ["Equipos", "asignados con etiquetas"], ["Fechas", "de inicio y fin"]], columns: [["Por planear", [["Expo de la industria", "Hotel · Vuelo · Auto de alquiler"], ["Cumbre de socios", "Etiqueta del equipo · Lista de viaje"]]], ["En curso", [["Conferencia de clientes", "Reservando el viaje"], ["Feria regional", "Equipo de operaciones asignado"]]], ["Listo", [["Muestra de primavera", "Lista completa"], ["Foro de liderazgo", "Fechas y equipo confirmados"]]]], later: "Sugerencia de OS Operator", update: "“Los eventos duran más de un día. Agreguemos un campo de fecha de finalización.”", updated: "El tablero se amplió para acompañar el trabajo real" },
  development: { kicker: "Software que crece contigo", title: "OS Developer es el ingeniero de tu equipo de agentes.", body: "Cuando el negocio necesita algo más que una configuración o plantilla, OS Developer puede modificar y ampliar el propio OperateOS. Describe el resultado, revisa la propuesta y recibe un cambio probado para aprobar, sin esperar el calendario de un proveedor de SaaS.", mode: "OS Developer", connected: "Listo para crear", agentLabel: "OS Developer", history: "Mejoras del negocio", next: "El sistema sigue mejorando", historyItems: [["Fin de los eventos", "Extensión del producto · entregada"], ["Alta de proveedores", "Flujo personalizado · listo"], ["Bandeja de entrada", "Módulo conectado · activo"]], user: "Nuestros eventos necesitan una fecha final, no solo una fecha de entrega.", agent: "Ampliaré la tarjeta para que cada evento tenga fechas de inicio y fin, mantendré el calendario consistente y devolveré el cambio para revisión.", progress: ["Necesidad entendida", "Experiencia actualizada", "Flujo existente preservado", "Probado y listo para revisión"], newCapability: "Creado para el negocio", module: "Rango de fechas del evento", moduleBody: "Una mejora específica que ahora forma parte del sistema de la empresa.", appears: "Revisado antes de publicarse" },
  modulesSection: { kicker: "Por ejemplo, y mucho más", title: "Empieza con lo esencial. Agrega lo que importa.", body: "OperateOS es un ERP y CRM en constante desarrollo. Estos son ejemplos de lo que existe hoy, no los límites del producto. Seguiremos ampliando el sistema con las capacidades más valiosas del mejor SaaS, y tu empresa podrá extenderlo para el trabajo que la hace única.", aria: "Ejemplos de módulos de OperateOS", workspaceKicker: "Hecho para cualquier pequeño negocio", workspaceTitle: "Sectores distintos. Flujos distintos. Una base adaptable.", workspaceBody: "Una tienda, estudio, contratista, clínica o empresa de servicios no debería trabajar de la misma forma. Cada espacio conserva sus personas, archivos, conocimiento, marca y contexto de los agentes mientras la administración se mantiene organizada.", workspaceAria: "Ejemplos de espacios separados para pequeños negocios", workspaceTypes: ["Comercio", "Creativo", "Servicios"], sharedAdmin: "Una instalación privada" },
  modules: [["Inicio", "Tu visión de la operación"], ["Bandeja de entrada", "Chat web, SMS y correo en un solo lugar"], ["Pipeline", "Oportunidades y próximos pasos"], ["Relaciones", "Contactos, empresas e historial"], ["Anuncios", "Google y Meta con acciones controladas"], ["Tableros", "Kanban, calendario, plantillas y listas"], ["Conocimiento", "La fuente de verdad de tu empresa"], ["Espacios", "Equipos, marcas y contextos separados"], ["Chat con agentes", "Pide, revisa y actúa en un solo lugar"]],
  beta: { kicker: "Ahora en pruebas beta", title: "Ayuda a crear el sistema que siempre quisiste para tu negocio.", body: "Estamos trabajando con pequeños negocios de cualquier sector para probar OperateOS en operaciones reales. Únete a la lista de espera y cuéntanos dónde te frena tu software actual, o contáctanos para recibir más información.", promiseLabel: "Qué significa beta", promise: "Flujos reales, colaboración cercana y un producto que mejora a partir de lo que los pequeños negocios necesitan de verdad, no de una lista genérica de funciones.", cardsAria: "Formas de conectar con OperateOS", cards: [["01", "Unirme a la lista de espera", "Cuéntanos sobre tu negocio y los problemas que quieres resolver.", "Unirme a la lista", "mailto:hello@operaos.ai?subject=Lista%20de%20espera%20beta%20de%20OperateOS"], ["02", "Contactarnos", "Haz preguntas, conversa sobre tus necesidades o solicita más información.", "Enviar un mensaje", "mailto:hello@operaos.ai?subject=Informaci%C3%B3n%20sobre%20OperateOS"]], noteLabel: "Creado con usuarios beta", noteTitle: "Tu trabajo real guía lo que viene.", noteBody: "Estamos ampliando OperateOS con cuidado, priorizando capacidades útiles, flujos confiables y cambios que facilitan la gestión de los pequeños negocios." },
  ownership: { kicker: "Una mejor elección a largo plazo", lineOne: "Tu sistema.", lineTwo: "Tus datos.", lineThree: "Tu forma de ", emphasis: "trabajar.", body: "En vez de alquilar las mismas herramientas rígidas para siempre, crea un sistema de información que se vuelve más valioso a medida que aprende del negocio y se adapta a él.", proofs: [["Funciona en tu computadora", "Tu negocio controla dónde viven OperateOS y sus registros."], ["Privado por diseño", "El conocimiento de la empresa permanece en el sistema controlado por el negocio."], ["Aprobación humana", "Las acciones importantes de los agentes esperan tu decisión."], ["Hecho para durar", "Las copias de seguridad y credenciales protegidas ayudan a cuidar el sistema."]], closing: "Deja de adaptarte al software antiguo.", closingSecond: "Empieza a crear el sistema que tu negocio merece.", access: "OperateOS · Pruebas beta", primaryCta: "Unirme a la lista de espera", secondaryCta: "Contactarnos" },
};

export const COPY: Record<Locale, Copy> = { en, "pt-BR": ptBR, "es-419": es419 };

export function normalizeLocale(value: string | null | undefined): Locale | null {
  if (!value) return null;
  const normalized = value.toLowerCase();
  if (normalized === "pt-br" || normalized.startsWith("pt")) return "pt-BR";
  if (normalized === "es-419" || normalized.startsWith("es")) return "es-419";
  if (normalized === "en" || normalized.startsWith("en")) return "en";
  return null;
}
